ROBOCOPY D:\pstwin\BMP\ D:\Pstwin_x64\BMP\ /S /B /XF *.EXE *.ZIP *.RAR
ROBOCOPY D:\pstwin\CONSULTA\ D:\Pstwin_x64\CONSULTA\ /S /B /XF *.EXE *.ZIP *.RAR
ROBOCOPY D:\pstwin\CUR\ D:\Pstwin_x64\CUR\ /S /B /XF *.EXE *.ZIP *.RAR
ROBOCOPY D:\pstwin\DLL\ D:\Pstwin_x64\DLL\ /S /B /XF *.EXE *.ZIP *.RAR
ROBOCOPY D:\pstwin\FRX\ D:\Pstwin_x64\FRX\ /S /B /XF *.EXE *.ZIP *.RAR
ROBOCOPY D:\pstwin\H\ D:\Pstwin_x64\H\ /S /B /XF *.EXE *.ZIP *.RAR
ROBOCOPY D:\pstwin\ICO\ D:\Pstwin_x64\ICO\ /S /B /XF *.EXE *.ZIP *.RAR
ROBOCOPY D:\pstwin\MACRO\ D:\Pstwin_x64\MACRO\ /S /B /XF *.EXE *.ZIP *.RAR
ROBOCOPY D:\pstwin\MNX\ D:\Pstwin_x64\MNX\ /S /B /XF *.EXE *.ZIP *.RAR
ROBOCOPY D:\pstwin\PRG\ D:\Pstwin_x64\PRG\ /S /B /XF *.EXE *.ZIP *.RAR
ROBOCOPY D:\pstwin\SCX\ D:\Pstwin_x64\SCX\ /S /B /XF *.EXE *.ZIP *.RAR
ROBOCOPY D:\pstwin\VCX\ D:\Pstwin_x64\VCX\ /S /B /XF *.EXE *.ZIP *.RAR
ROBOCOPY D:\pstwin\temporal\PRECUADRE\ D:\Pstwin_x64\temporal\PRECUADRE\  /S /B /XF *.EXE *.ZIP *.RAR
ROBOCOPY "D:\pstwin\temporal\inclusion masiva" "D:\Pstwin_x64\temporal\inclusion masiva"  /S /B /XF *.EXE *.ZIP *.RAR










